# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/client.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protos/client.proto\"&\n\x12\x63riarPedidoRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\"#\n\x10\x63riarPedidoReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"`\n\x16modificarPedidoRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x0f\n\x07ordemId\x18\x02 \x01(\t\x12\x0f\n\x07produto\x18\x03 \x01(\t\x12\x12\n\nquantidade\x18\x04 \x01(\x05\"\'\n\x14modificarPedidoReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"8\n\x13listarPedidoRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x0f\n\x07ordemId\x18\x02 \x01(\t\"$\n\x11listarPedidoReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\x14listarPedidosRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\"%\n\x12listarPedidosReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"8\n\x13\x61pagarPedidoRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x0f\n\x07ordemId\x18\x02 \x01(\t\"$\n\x11\x61pagarPedidoReply\x12\x0f\n\x07message\x18\x01 \x01(\t\".\n\x1a\x61\x64icionaPedidoTesteRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\"+\n\x18\x61\x64icionaPedidoTesteReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xc5\x02\n\x06\x43lient\x12\x35\n\x0b\x63riarPedido\x12\x13.criarPedidoRequest\x1a\x11.criarPedidoReply\x12\x41\n\x0fmodificarPedido\x12\x17.modificarPedidoRequest\x1a\x15.modificarPedidoReply\x12\x38\n\x0clistarPedido\x12\x14.listarPedidoRequest\x1a\x12.listarPedidoReply\x12\x38\n\x0c\x61pagarPedido\x12\x14.apagarPedidoRequest\x1a\x12.apagarPedidoReply\x12M\n\x13\x61\x64icionaPedidoTeste\x12\x1b.adicionaPedidoTesteRequest\x1a\x19.adicionaPedidoTesteReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.client_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CRIARPEDIDOREQUEST._serialized_start=23
  _CRIARPEDIDOREQUEST._serialized_end=61
  _CRIARPEDIDOREPLY._serialized_start=63
  _CRIARPEDIDOREPLY._serialized_end=98
  _MODIFICARPEDIDOREQUEST._serialized_start=100
  _MODIFICARPEDIDOREQUEST._serialized_end=196
  _MODIFICARPEDIDOREPLY._serialized_start=198
  _MODIFICARPEDIDOREPLY._serialized_end=237
  _LISTARPEDIDOREQUEST._serialized_start=239
  _LISTARPEDIDOREQUEST._serialized_end=295
  _LISTARPEDIDOREPLY._serialized_start=297
  _LISTARPEDIDOREPLY._serialized_end=333
  _LISTARPEDIDOSREQUEST._serialized_start=335
  _LISTARPEDIDOSREQUEST._serialized_end=375
  _LISTARPEDIDOSREPLY._serialized_start=377
  _LISTARPEDIDOSREPLY._serialized_end=414
  _APAGARPEDIDOREQUEST._serialized_start=416
  _APAGARPEDIDOREQUEST._serialized_end=472
  _APAGARPEDIDOREPLY._serialized_start=474
  _APAGARPEDIDOREPLY._serialized_end=510
  _ADICIONAPEDIDOTESTEREQUEST._serialized_start=512
  _ADICIONAPEDIDOTESTEREQUEST._serialized_end=558
  _ADICIONAPEDIDOTESTEREPLY._serialized_start=560
  _ADICIONAPEDIDOTESTEREPLY._serialized_end=603
  _CLIENT._serialized_start=606
  _CLIENT._serialized_end=931
# @@protoc_insertion_point(module_scope)
