# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import client_pb2 as protos_dot_client__pb2


class ClientStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.criarPedido = channel.unary_unary(
                '/Client/criarPedido',
                request_serializer=protos_dot_client__pb2.criarPedidoRequest.SerializeToString,
                response_deserializer=protos_dot_client__pb2.criarPedidoReply.FromString,
                )
        self.modificarPedido = channel.unary_unary(
                '/Client/modificarPedido',
                request_serializer=protos_dot_client__pb2.modificarPedidoRequest.SerializeToString,
                response_deserializer=protos_dot_client__pb2.modificarPedidoReply.FromString,
                )
        self.listarPedido = channel.unary_unary(
                '/Client/listarPedido',
                request_serializer=protos_dot_client__pb2.listarPedidoRequest.SerializeToString,
                response_deserializer=protos_dot_client__pb2.listarPedidoReply.FromString,
                )
        self.apagarPedido = channel.unary_unary(
                '/Client/apagarPedido',
                request_serializer=protos_dot_client__pb2.apagarPedidoRequest.SerializeToString,
                response_deserializer=protos_dot_client__pb2.apagarPedidoReply.FromString,
                )
        self.adicionaPedidoTeste = channel.unary_unary(
                '/Client/adicionaPedidoTeste',
                request_serializer=protos_dot_client__pb2.adicionaPedidoTesteRequest.SerializeToString,
                response_deserializer=protos_dot_client__pb2.adicionaPedidoTesteReply.FromString,
                )


class ClientServicer(object):
    """Missing associated documentation comment in .proto file."""

    def criarPedido(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def modificarPedido(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listarPedido(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def apagarPedido(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def adicionaPedidoTeste(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'criarPedido': grpc.unary_unary_rpc_method_handler(
                    servicer.criarPedido,
                    request_deserializer=protos_dot_client__pb2.criarPedidoRequest.FromString,
                    response_serializer=protos_dot_client__pb2.criarPedidoReply.SerializeToString,
            ),
            'modificarPedido': grpc.unary_unary_rpc_method_handler(
                    servicer.modificarPedido,
                    request_deserializer=protos_dot_client__pb2.modificarPedidoRequest.FromString,
                    response_serializer=protos_dot_client__pb2.modificarPedidoReply.SerializeToString,
            ),
            'listarPedido': grpc.unary_unary_rpc_method_handler(
                    servicer.listarPedido,
                    request_deserializer=protos_dot_client__pb2.listarPedidoRequest.FromString,
                    response_serializer=protos_dot_client__pb2.listarPedidoReply.SerializeToString,
            ),
            'apagarPedido': grpc.unary_unary_rpc_method_handler(
                    servicer.apagarPedido,
                    request_deserializer=protos_dot_client__pb2.apagarPedidoRequest.FromString,
                    response_serializer=protos_dot_client__pb2.apagarPedidoReply.SerializeToString,
            ),
            'adicionaPedidoTeste': grpc.unary_unary_rpc_method_handler(
                    servicer.adicionaPedidoTeste,
                    request_deserializer=protos_dot_client__pb2.adicionaPedidoTesteRequest.FromString,
                    response_serializer=protos_dot_client__pb2.adicionaPedidoTesteReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Client', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Client(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def criarPedido(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Client/criarPedido',
            protos_dot_client__pb2.criarPedidoRequest.SerializeToString,
            protos_dot_client__pb2.criarPedidoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def modificarPedido(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Client/modificarPedido',
            protos_dot_client__pb2.modificarPedidoRequest.SerializeToString,
            protos_dot_client__pb2.modificarPedidoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listarPedido(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Client/listarPedido',
            protos_dot_client__pb2.listarPedidoRequest.SerializeToString,
            protos_dot_client__pb2.listarPedidoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def apagarPedido(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Client/apagarPedido',
            protos_dot_client__pb2.apagarPedidoRequest.SerializeToString,
            protos_dot_client__pb2.apagarPedidoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def adicionaPedidoTeste(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Client/adicionaPedidoTeste',
            protos_dot_client__pb2.adicionaPedidoTesteRequest.SerializeToString,
            protos_dot_client__pb2.adicionaPedidoTesteReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
